### ISSUE TITLE
Getting Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by tthiatma** [qetza/vsts-xdttransform-task#10]
Hello,

I am trying to convert a config file from 

```
<?xml version="1.0" encoding="utf-8"?>
<packagingConfig />
```

to

```
<?xml version="1.0" encoding="utf-8"?>
<packagingConfig xmlns:config="urn:telerik:sitefinity:configuration" xmlns:type="urn:telerik:sitefinity:configuration:type" config:version="10.1.6500.0" packagingMode="Target" />
```

so I created below xdt file 
```
<?xml version="1.0" encoding="utf-8"?>
<packagingConfig
    xmlns:xdt="http://schemas.microsoft.com/XML-Document-Transform"
    xmlns:config="urn:telerik:sitefinity:configuration" 
    xmlns:type="urn:telerik:sitefinity:configuration:type" 
    config:version="10.1.6500.0" 
    packagingMode="Target"
    xdt:Transform="Replace"/>
```

When doing a build in vsts, it throws  below error:

2017-10-18T22:06:07.3442982Z ##[error]Exception calling "Save" with "1" argument(s): "Object reference not set to an instance of an object."
![image](https://user-images.githubusercontent.com/4022533/31745922-9bc2cb92-b419-11e7-9d4a-0e303fe8c673.png)

Is there something wrong with my xdt file?

Please help on this.

Thanks,
Tonny

**Comment by tthiatma** [comment]
I turned on the system.debug and below is the log

```
2017-10-19T17:17:20.3558153Z ##[debug]Evaluating condition for step: 'DataConfig, AuthConfig, SiteSync'
2017-10-19T17:17:20.3558153Z ##[debug]Evaluating: succeeded()
2017-10-19T17:17:20.3558153Z ##[debug]Evaluating succeeded:
2017-10-19T17:17:20.3558153Z ##[debug]=> (Boolean) True
2017-10-19T17:17:20.3558153Z ##[debug]Expanded: True
2017-10-19T17:17:20.3558153Z ##[debug]Result: True
2017-10-19T17:17:20.3558153Z ##[section]Starting: DataConfig, AuthConfig, SiteSync
2017-10-19T17:17:20.3558153Z ==============================================================================
2017-10-19T17:17:20.3558153Z Task         : XDT Transform
2017-10-19T17:17:20.3558153Z Description  : Apply XDT transforms on XML files
2017-10-19T17:17:20.3558153Z Version      : 2.1.0
2017-10-19T17:17:20.3558153Z Author       : Guillaume Rouchon
2017-10-19T17:17:20.3558153Z Help         : v2.1.0, [More Information](https://github.com/qetza/vsts-xdttransform-task#readme)
2017-10-19T17:17:20.3558153Z ==============================================================================
2017-10-19T17:17:24.3937772Z ##[debug]VstsTaskSdk 0.7.1 commit f990f8d8df6197b1cfcec01031ba014ad4905681
2017-10-19T17:17:24.4988197Z ##[debug]Entering D:\a\_tasks\xdttransform_98012758-c053-475d-9d6a-fd0773c39e09\2.1.0\transform.ps1.
2017-10-19T17:17:24.5547963Z ##[debug]INPUT_WORKINGFOLDER: 'd:\a\1\s\SitefinityWebApp\App_Data\Sitefinity\Configuration\'
2017-10-19T17:17:24.5577776Z ##[debug]INPUT_TRANSFORMS: 'DataConfig.DeployMaster.config => DataConfig.config
2017-10-19T17:17:24.5597772Z ##[debug]AuthenticationConfig.DeployMaster.config => AuthenticationConfig.config
2017-10-19T17:17:24.5627767Z ##[debug]SiteSyncConfig.DeployMaster.config => SiteSyncConfig.config
2017-10-19T17:17:24.5637764Z ##[debug]PackagingConfig.DeployMaster.config => PackagingConfig.config'
2017-10-19T17:17:25.1005864Z Applying transformations 'd:\a\1\s\SitefinityWebApp\App_Data\Sitefinity\Configuration\DataConfig.DeployMaster.config' on file 'd:\a\1\s\SitefinityWebApp\App_Data\Sitefinity\Configuration\DataConfig.config'...
2017-10-19T17:17:25.2200391Z Applying transformations 'd:\a\1\s\SitefinityWebApp\App_Data\Sitefinity\Configuration\AuthenticationConfig.DeployMaster.config' on file 'd:\a\1\s\SitefinityWebApp\App_Data\Sitefinity\Configuration\AuthenticationConfig.config'...
2017-10-19T17:17:25.2320382Z Applying transformations 'd:\a\1\s\SitefinityWebApp\App_Data\Sitefinity\Configuration\SiteSyncConfig.DeployMaster.config' on file 'd:\a\1\s\SitefinityWebApp\App_Data\Sitefinity\Configuration\SiteSyncConfig.config'...
2017-10-19T17:17:25.2370617Z Applying transformations 'd:\a\1\s\SitefinityWebApp\App_Data\Sitefinity\Configuration\PackagingConfig.DeployMaster.config' on file 'd:\a\1\s\SitefinityWebApp\App_Data\Sitefinity\Configuration\PackagingConfig.config'...
2017-10-19T17:17:25.2850538Z ##[debug]Leaving D:\a\_tasks\xdttransform_98012758-c053-475d-9d6a-fd0773c39e09\2.1.0\transform.ps1.
2017-10-19T17:17:25.2890590Z ##[debug]Caught exception from task script.
2017-10-19T17:17:25.2930627Z ##[debug]Error record:
2017-10-19T17:17:25.3670385Z ##[debug]% : Exception calling "Save" with "1" argument(s): "Object reference not set to an instance of an object."
2017-10-19T17:17:25.3680395Z ##[debug]At D:\a\_tasks\xdttransform_98012758-c053-475d-9d6a-fd0773c39e09\2.1.0\transform.ps1:73 char:40
2017-10-19T17:17:25.3690616Z ##[debug]+     $transforms -split "(?:`n`r?)|," | % {
2017-10-19T17:17:25.3700397Z ##[debug]+                                        ~~~
2017-10-19T17:17:25.3720381Z ##[debug]    + CategoryInfo          : NotSpecified: (:) [ForEach-Object], MethodInvocationException
2017-10-19T17:17:25.3730589Z ##[debug]    + FullyQualifiedErrorId : DotNetMethodException,Microsoft.PowerShell.Commands.ForEachObjectCommand
2017-10-19T17:17:25.3740605Z ##[debug] 
2017-10-19T17:17:25.3760620Z ##[debug]Script stack trace:
2017-10-19T17:17:25.3800634Z ##[debug]at _ApplyTransform, D:\a\_tasks\xdttransform_98012758-c053-475d-9d6a-fd0773c39e09\2.1.0\transform.ps1: line 52
2017-10-19T17:17:25.3820387Z ##[debug]at <ScriptBlock>, D:\a\_tasks\xdttransform_98012758-c053-475d-9d6a-fd0773c39e09\2.1.0\transform.ps1: line 112
2017-10-19T17:17:25.3830616Z ##[debug]at <ScriptBlock>, D:\a\_tasks\xdttransform_98012758-c053-475d-9d6a-fd0773c39e09\2.1.0\transform.ps1: line 73
2017-10-19T17:17:25.3840641Z ##[debug]at <ScriptBlock>, <No file>: line 1
2017-10-19T17:17:25.3850402Z ##[debug]at <ScriptBlock>, <No file>: line 22
2017-10-19T17:17:25.3870408Z ##[debug]at <ScriptBlock>, <No file>: line 18
2017-10-19T17:17:25.3880575Z ##[debug]at <ScriptBlock>, <No file>: line 1
2017-10-19T17:17:25.3900564Z ##[debug]Exception:
2017-10-19T17:17:25.4330619Z ##[debug]System.Management.Automation.MethodInvocationException: Exception calling "Save" with "1" argument(s): "Object reference not set to an instance of an object." ---> System.NullReferenceException: Object reference not set to an instance of an object.
2017-10-19T17:17:25.4350388Z ##[debug]   at Microsoft.Web.XmlTransform.XmlFormatter.ComputeOneTab()
2017-10-19T17:17:25.4360497Z ##[debug]   at Microsoft.Web.XmlTransform.XmlFormatter.ComputeCurrentAttributeIndent()
2017-10-19T17:17:25.4370390Z ##[debug]   at Microsoft.Web.XmlTransform.XmlAttributePreservationDict.UpdatePreservationInfo(XmlAttributeCollection updatedAttributes, XmlFormatter formatter)
2017-10-19T17:17:25.4640391Z ##[debug]   at Microsoft.Web.XmlTransform.XmlFormatter.HandleStartElement(XmlNode node)
2017-10-19T17:17:25.4650394Z ##[debug]   at Microsoft.Web.XmlTransform.XmlFormatter.HandleElement(XmlNode node)
2017-10-19T17:17:25.4690391Z ##[debug]   at Microsoft.Web.XmlTransform.XmlFormatter.FormatLoop(XmlNode parentNode)
2017-10-19T17:17:25.4990476Z ##[debug]   at Microsoft.Web.XmlTransform.XmlFormatter.Format(XmlDocument document)
2017-10-19T17:17:25.4990476Z ##[debug]   at Microsoft.Web.XmlTransform.XmlFileInfoDocument.Save(String filename)
2017-10-19T17:17:25.4990476Z ##[debug]   at Save(Object , Object[] )
2017-10-19T17:17:25.4990476Z ##[debug]   at System.Management.Automation.DotNetAdapter.AuxiliaryMethodInvoke(Object target, Object[] arguments, MethodInformation methodInformation, Object[] originalArguments)
2017-10-19T17:17:25.4990476Z ##[debug]   --- End of inner exception stack trace ---
2017-10-19T17:17:25.4990476Z ##[debug]   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
2017-10-19T17:17:25.4990476Z ##[debug]   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
2017-10-19T17:17:25.4990476Z ##[debug]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2017-10-19T17:17:25.4990476Z ##[debug]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2017-10-19T17:17:25.4990476Z ##[debug]   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
2017-10-19T17:17:25.4990476Z ##[debug]   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
2017-10-19T17:17:25.4990476Z ##[debug]   at System.Management.Automation.ScriptBlock.InvokeWithPipeImpl(ScriptBlockClauseToInvoke clauseToInvoke, Boolean createLocalScope, Dictionary`2 functionsToDefine, List`1 variablesToDefine, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Pipe outputPipe, InvocationInfo invocationInfo, Object[] args)
2017-10-19T17:17:25.4990476Z ##[debug]   at System.Management.Automation.ScriptBlock.<>c__DisplayClassa.<InvokeWithPipe>b__8()
2017-10-19T17:17:25.4990476Z ##[debug]   at System.Management.Automation.Runspaces.RunspaceBase.RunActionIfNoRunningPipelinesWithThreadCheck(Action action)
2017-10-19T17:17:25.4990476Z ##[debug]   at System.Management.Automation.ScriptBlock.InvokeWithPipe(Boolean useLocalScope, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Pipe outputPipe, InvocationInfo invocationInfo, Boolean propagateAllExceptionsToTop, List`1 variablesToDefine, Dictionary`2 functionsToDefine, Object[] args)
2017-10-19T17:17:25.4990476Z ##[debug]   at System.Management.Automation.ScriptBlock.InvokeUsingCmdlet(Cmdlet contextCmdlet, Boolean useLocalScope, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Object[] args)
2017-10-19T17:17:25.4990476Z ##[debug]   at Microsoft.PowerShell.Commands.ForEachObjectCommand.ProcessRecord()
2017-10-19T17:17:25.4990476Z ##[debug]   at System.Management.Automation.CommandProcessor.ProcessRecord()
2017-10-19T17:17:25.5530391Z ##[error]Exception calling "Save" with "1" argument(s): "Object reference not set to an instance of an object."
2017-10-19T17:17:25.5530391Z ##[debug]Processed: ##vso[task.logissue type=error]Exception calling "Save" with "1" argument(s): "Object reference not set to an instance of an object."
2017-10-19T17:17:25.5530391Z ##[debug]Processed: ##vso[task.complete result=Failed]
2017-10-19T17:17:25.5650382Z ##[section]Finishing: DataConfig, AuthConfig, SiteSync
```

**Comment by qetza** [comment]
Hi Tonny,

The issue seems to come from a bug in the library Microsoft.Web.XmlTransform i'm using. If you do a transformation on the root node it's failing during save.
Can you move the attributes to another node?

Note that when doing my tests i saw that the library doesn't handle well inserting or keeping attributes with custom xml namespace if those are not defined in the source XML. I was able to make the transformation work with the following files:

```xml
<?xml version="1.0" encoding="utf-8"?>
<packagingConfig xmlns:config="urn:telerik:sitefinity:configuration" 
                 xmlns:type="urn:telerik:sitefinity:configuration:type"/>
```

```xml
<?xml version="1.0" encoding="utf-8"?>
<packagingConfig
    xmlns:xdt="http://schemas.microsoft.com/XML-Document-Transform"
    xmlns:config="urn:telerik:sitefinity:configuration"
    xmlns:type="urn:telerik:sitefinity:configuration:type">
    <root config:version="10.1.6500.0" 
          packagingMode="Target"
          xdt:Transform="Insert" />
</packagingConfig>
```

**Comment by tthiatma** [comment]
Hi Qetza,

Thank you for the suggestion. Unfortunately, I don't have control over the code that actually read the xml.

I ended up doing below to make it work

```
<?xml version="1.0" encoding="utf-8"?>
<packagingConfig xmlns:config="urn:telerik:sitefinity:configuration"
xmlns:type="urn:telerik:sitefinity:configuration:type"
config:version="10.1.6500.0" />

```
```
<?xml version="1.0" encoding="utf-8"?>
<packagingConfig
xmlns:xdt="http://schemas.microsoft.com/XML-Document-Transform"
xmlns:config="urn:telerik:sitefinity:configuration"
xmlns:type="urn:telerik:sitefinity:configuration:type"
config:version="10.1.6500.0"
packagingMode="Target"
xdt:Transform="SetAttributes(packagingMode)" />
```
